spring.application.name=gestionale-concessionaria

server.port=8081
app.nome-concessionaria=AutoMax
app.email-supporto=support@automax.com
app.max-veicoli-per-pagina=10

spring.datasource.url=jdbc:h2:file:./data/concessionaria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:cambiami-con-una-stringa-lunga-almeno-32-caratteri-casuale-e-segreta}
jwt.expiration-ms=3600000